### ISSUE TITLE
enum column creation raises asyncpg.exceptions.UndefinedObjectError

### ISSUE THREAD

**Issue by NCPlayz** [bijij/Donphan#4]
Using the custom enum example provided in the repository, asyncpg raises this error:
```
Traceback (most recent call last):
  File "concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "<console>", line 2, in <module>
    await MyTable.create(conn) 
  File "donphan\utils.py", line 132, in wrapped
    return await func(cls, connection, *args, **kwargs)
  File "donphan\_creatable.py", line 133, in create
    await connection.execute(query)
  File "asyncpg\connection.py", line 297, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg\protocol\protocol.pyx", line 338, in query
asyncpg.exceptions.UndefinedObjectError: type "public.my_enum" does not exist
```

**Comment by NCPlayz** [comment]
It seems like the only way to create the enum value is by accessing the column and creating it through the EnumType subclass: `MyTable.value.sql_type.create(conn)`. Let me know if there's an alternative method.

**Comment by bijij** [comment]
using `Table.create` will now automatically create and register enum types as of v4.8.0
